baseURL: https://peter-funny-portfolio.netlify.app
languageCode: en-us
title: Portfolio website for Kostis Christodoulou
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: αρχή
#     subtitle: |-
#      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
#      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Peter, I think it means rock in Hebrew
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Baker Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: pszkolnik.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 07447939262
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Kostis Enterprises Limited
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
  #    - icon: fa-twitter
  #      label: Twitter
  #      url: https://www.twitter.com
  #    - icon: fa-facebook
  #      label: Facebook
  #      url: https://www.facebook.com
  #    - icon: fa-instagram
  #      label: Instagram
  #      url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/thor4fun/my_website
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/szkolnik
  image: ''
  name: My name!
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs?
        url: blogs
      - name: Ipsum Blog
        url: blogs/ipsum
      - name: Elements!
        url: elements.html
    menu: Menu
    subtitle: In London
    title: Made
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Wavey wave
        title: One Title
        url: blogs/risk_return
      - image: pic02.jpg
        subtitle: Rolling ball
        title: Two Title
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Kind of heavy
        title: Three Title
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Its a good joke
        title: Four Title
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Future of work
        title: Five Title
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Alternative career
        title: Probably Six Title
        url: blogs/ipsum
  two:
    buttonText: να σταματήσει
    enable: yes
    subtitle: "This is the best course in the world.
      \r\n    It most certainly is. \r\n    One should try it.
      Certainly.\r\n    Ok, thats all."
    title: Is this the best course?
    url: blogs

#<!-- -->
#```
#markup: 
#  goldmark: 
#    renderer: 
#      unsafe: true
#```